### PR TITLE
Resolve #2305 by fixing broken 'matchers' link

### LINKED ISSUE #2305: Documentation: Link from "spies" to "matchers" broken
**Describe the bug**
On the documentation page for spies, the link to the documentation page for matchers is broken.

**To Reproduce**
1. Go to the documentation for Spies: https://sinonjs.org/releases/latest/spies/
2. Click on the link: (see <a href="matchers">matchers</a>)

The target URL https://sinonjs.org/releases/latest/spies/matchers results in a 404 error.

**Expected behavior**
I assume the link should direct to: https://sinonjs.org/releases/latest/matchers/

**Context**

* Browser: Tested with Safari and Chrome on macOS. The issue occurs on both browsers.

**Note**: The link to the matchers page appears 3 times on the "spies" page

### PR DESCRIPTION
**Pull request by sjoseph7**
#### Purpose (TL;DR) 
Resolve #2305 by fixing broken 'matchers' link

 #### Solution 
Fix broken links (3 of them)

 #### How to verify 
1. Check out this branch
2. Open file
3. Observe markdown
4. Hover over links to confirm accuracy

 #### Checklist for author
- [x] `npm run lint` passes
- [x] References to standard library functions are [cached](https://github.com/sinonjs/sinon/pull/1523).

### CODE REVIEW

**Comment by mroderick** [comment]
Thank you for your pull request.

For historical reasons, the documentation has an entire tree for each. single. version.

https://github.com/sinonjs/sinon/tree/master/docs/_releases

Would you mind fixing the documentation for the other releases also?

**Comment by sjoseph7** [comment]
Yikes... there's so many lol 😅
They should all be good now 👍🏾

**Comment by fatso83** [comment]
Yeah, we were supposed to do something about that, since this approach does not really scale. I was doing something to keep it down to just the major versions, but never finished it.

**Comment by sjoseph7** [comment]
@fatso83 let me know if it's something I can help with

**Comment by fatso83** [comment]
You are more than welcome to finish what I started: https://github.com/fatso83/sinon/tree/only-major-version-docs

**Pull request merged**
