### PR TITLE
Revert esm for 5x

### PR DESCRIPTION
**Pull request by mroderick**
#### How to verify - mandatory
1. Check out this branch
2. `npm install`
3. <your-steps-here>

#### Checklist for author

- [ ] `npm run lint` passes
- [ ] References to standard library functions are [cached](https://github.com/sinonjs/sinon/pull/1523).

### CODE REVIEW

**Comment by fatso83** [comment]
it was quite intentional i didn't make that a PR, because I don't think it should revert the changes on the master branch.

**Comment by mroderick** [comment]
Apologies, I'll close it and let you do it properly

**Comment by fatso83** [comment]
5.1.1 is out :)

**Comment by mroderick** [comment]
> 5.1.1 is out :)

Thank you 👍

**Pull request closed without merging**
