### PR TITLE
Fix #1714: Add .callback and .lastArg to fake and call

### LINKED ISSUE #1714: sinon@next: Provide a way to invoke callbacks on fakes
This is a follow up issue from the discussion on #1696.

The Sinon spy and stub APIs have these functions:

- `yield` (aliased as `invokeCallback`)
- `yieldOn`
- `yieldTo`
- `yieldToOn`
- `callArg` (aliased as `callArgWith`)
- `callArgOn` (aliased as `callArgOnWith`)

They all intend to invoke callbacks that were passed to the spy or stub as an argument.

Instead of providing various ways to invoke arguments as functions, we could expose them in a more convenient way and let users invoke the functions. This allows to make use of `.call` and `.apply` to change the function scope.

Currently, arguments can be accessed through calls, e.g. the `fake.firstCall.args` array.

I would like to propose that we expose more references to arguments in order to avoid having to add all of the above methods to the new `fake` api:

- `fake.callback`: Referring to the last argument being passed to the fake in the last call, if it's a function. Otherwise this property does not exist.
- `fake.lastArg`: Referring to the last argument being passed to the fake in the last call.
- `fake.getCall(n).callback`: Referring to the last argument being passed to this specific call, if it's a function. Otherwise this property does not exist.
- `fake.getCall(n).lastArg`: Referring to the last argument being passed to this specific call.

The "legacy" API functions would map to the new fake API as follows:

| Legacy | Fake API |
|----|----|
| `yield(a, b, c)` | `fake.callback(a, b, c)` |
| `yieldOn(scope, a, b, c)` | `fake.callback.call(scope, a, b, c)` |
| `yieldTo(property, a, b, c)` | `fake.lastArg[property](a, b, c)` |
| `yieldToOn(property, scope, a, b, c)` | `fake.lastArg[property].call(scope, a, b, c)` |
| `callArg(index, a, b, c)` | `fake.lastCall.args[index](a, b, c)` |
| `callArgOn(index, scope, a, b, c)` | `fake.lastCall.args[index].call(scope, a, b, c)` |

The difference between `fake.lastArg` and `fake.callback` is purely semantical and implies a type check for `fake.callback`. I'm suggesting this, because it would be weird to have an object under `fake.callback`. On the other hand, `fake.lastArg()` doesn't read very nice.

### PR DESCRIPTION
**Pull request by mroderick**
This PR is a solution for #1714 

@mantoni does this match your idea outlined in #1714? If it does, then I'll take a stab at writing some documentation for it.

### CODE REVIEW

**Comment by mroderick** [comment]
I've merged the branch into `next`. I'll write some documentation for it next. Do you want to take it for a spin in one of your projects, to see that it works as expected?

**Comment by mantoni** [comment]
Sure will do, but don‘t expect anything before Friday 🤖

**Comment by fatso83** [comment]
Does this mean closing #1714 should wait until the docs are in place?

**Comment by mroderick** [comment]
Yes please. I have some docs in a branch, however I'd like to add them upstream, so we don't end up in rebase hell

**Comment by mantoni** [comment]
I played with this in a small project (only a dozend tests) where I'm trying to use the newly introduced APIs exclusively. With this change, it works great! It was the last missing bit 🎉

The features I've been using are:

- `sinon` global sandbox with `sinon.restore()` called after each test
- `sinon.replace(...)`
- `sinon.fake()`
- `sinon.fake.returns(...)`
- `sinon.fake.yields(...)`
- `fake.callback(...)`
- `call.callback(...)`

I've been mixing those with fake timers and various `sinon.assert` functions.

I like the API. The resulting test code reads very well and I didn't find any new issues. 👍 

@mroderick If you're happy the current state, you could cut another `sinon.5.0.0-next` release and I'll refactor an open source project to use our new toys. Can't share the project I've been using as a playground (yet).

**Comment by mroderick** [comment]
Thank you for the feedback. 

I am working on a couple of pull requests:

* add `lastArg` and `callback` to `spyCall` (#1759)
* Improve documentation for fakes and spyCall (not opened yet)

Once we get those in, then I think we should cut a new `next` and focus on getting documentation ready for the new major release.

**Comment by mroderick** [comment]
I've pushed a new branch `next.4`, which has all changes from `master` up to `sinon@4.5.0` and all of `next`, including a commit to add documentation for `fake().lastArg` and `fake().callback()`.

Could you try it out in your playground? If it works there, then I think we can publish this as `next.4`, and then focus our efforts on finishing documentation.

What do you think @mantoni?

**Comment by mroderick** [comment]
On a related note, I hate long running branches and always run into merge hell. I think we should use `next.4` branch going forwards.

**Comment by mantoni** [comment]
@mroderick It's looking good. I ran the branch in my playground and on a couple of other projects that use `sinon@4.x`. The only difference was the deprecation warning reminding me to migrate `sinon.sandbox.create` 👍

**Comment by mroderick** [comment]
```
$ npm install sinon@next --save-dev

> sinon@5.0.0-next.4 postinstall /private/tmp/next-install/node_modules/sinon
> node scripts/support-sinon.js

Have some ❤️ for Sinon? You can support the project via Open Collective:
 > https://opencollective.com/sinon/donate

+ sinon@5.0.0-next.4
```

**Comment by mantoni** [comment]
🎉  https://github.com/javascript-studio/studio-log/commit/ca85d2d8fa03d736a2804f30c16710e17e31e2b1

**Pull request merged**
