### PR TITLE
Update documentatation for older releases

### PR DESCRIPTION
**Pull request by mroderick**
This PR is a followup to #1610, #1613, where we removed deprecated methods from documentation ... but only for `docs/release-source`.

This PR removes the documentation from the documentation from all the releases.

As alway, read commits separately to keep a firm grasp on sanity.

### CODE REVIEW

**Comment by fatso83** [comment]
This will not fail if merging #1616 first, @mroderick.

**Comment by fatso83** [comment]
Why keep the docs for `sinon.restore(object);` (and others in the 2.x docs) if we deprecated the method? It's no longer officially supported.

**Comment by mroderick** [comment]
> Why keep the docs for sinon.restore(object); (and others in the 2.x docs) if we deprecated the method? It's no longer officially supported.

The were removed in 3.x, not 2.x

**Comment by mroderick** [comment]
Read the commit messages, Luke!

**Comment by fatso83** [comment]
I did :smiley_cat:  I just meant that even if they were _present_, it was just to ease transition for previous users, so in my mind they were already gone by the time we wrapped them with a deprecation helper in the pre-2.0 branch.

**Comment by mroderick** [comment]
Thanks.

Let's discuss a strategy for how long to keep documentation around when we deprecate things, and ***how** to keep it around.

**Pull request merged**
