### PR TITLE
Allow calling original function from stub. Closes #989

### LINKED ISSUE #989: Allow calling original function from stub
Seen related ticket #668 about spies, it would still be useful to stub a function only when called with certain parameters, allowing the call to reach to the original function otherwise.

```
sinon.stub(object, 'method')

  .withArgs('1')
  .returns('one')

  .callThrough() // default action, for any other arguments
```

```
sinon.stub(object, 'method')

  .withArgs('1')
  .returns('one')

  .withArgs(sinon.any.arguments) // same, with some syntactic sugar
  .callThrough()
```

One specific use case is to stub individual application configuration variables where they are accessed with a getter function (e.g.: `nconf.get()`).

Configuration objects can get quite large, so we would like to verify different behaviour in integration tests depending on a single configuration variable, but leaving the rest of the configuration untouched, whatever it is, as the rest of the application obviously still depends on it.

### PR DESCRIPTION
**Pull request by lucasfcosta**
## Purpose (TL;DR)

This aims to add the feature requested in #989 and tests for it.

Here's an example of the new feature's usage:

```js
var obj = {
  method: function foo() {
    return 'bar';
  }
};

var myStub = sinon.stub(object, 'method');

myStub.withArgs(1).returns('baz');
myStub.callThrough();

object.method(1); // 'baz'
object.method('not 1'); // 'bar'
```

Due to #817 it's not working in one-liners, but as soon as #1227 gets merged it will work, since that PR allows chaining.

## Solution

In order to implement this I had to change the `wrapMethod` module in order for it to keep a reference for the old method in the new one. I used the key `wrappedMethod` to hold the old method because I thought it was the most semantically valid name possible.

Then I created a new behavior called `callThrough` which adds a property called `callsThrough` to the behavior with the value `true`. 

Whenever the stub can't find any matching fakes for the provided arguments, it will call behavior's `invoke`, as you can see [here](https://github.com/sinonjs/sinon/blob/a6d8e1460e21e0b9cc9a28926b8a130c423cd09e/lib/sinon/spy.js#L195). The `callsThrough` property will then be used by the behavior's [invoke](https://github.com/sinonjs/sinon/blob/a6d8e1460e21e0b9cc9a28926b8a130c423cd09e/lib/sinon/behavior.js#L140) method in order to determine if it should invoke the original `wrappedMethod`.

Please notice that the `wrappedMethod` is invoked with `.apply` in order to keep bot the `this` reference and the arguments correct.

**The tests ensure that the following requirements are met when using `callThrough()`:**

* The original function should not be called if we've got arguments that match any fakes
* The original function should be invoked if the arguments do not match any fakes
* The original function should be invoked with the same arguments when the arguments do not match any fake
* The original function should be invoked with the same `this` reference when the arguments do not match any fake

## How to verify
1. Check out this branch (see github instructions below)
2. `npm install`
3. `npm run test`

Please let me know if you desire any further changes or if you disagree with anything. 😄 
Also, after this one I'd also like to solve #956, which is partially related (if you don't mind).

Thanks for reading! ❤️

### CODE REVIEW

**Comment by RodH257** [comment]
Just wanted to say this is great, really helped me out - thanks @lucasfcosta

**Comment by lucasfcosta** [comment]
That's great to hear, thanks @RodH257!
It's this kind of thing that makes me work on open source projects.
Have a nice day buddy 😃

**Comment by sakovias** [comment]
Appreciate this change!

**Comment by Attrash-Islam** [comment]
+1 :heart:

**Comment by karrtikr** [comment]
@lucasfcosta Really helped me out, thanks a lot! Hope you're doing well

**Pull request merged**
