### PR TITLE
Replaced switch statement in favor of object lookup

### PR DESCRIPTION
**Pull request by fearphage**
So this is a little easier to follow and it's more performant.

### CODE REVIEW

**Comment by mroderick** [comment]
> and it's more performant.

Have you measured it using http://benchmarkjs.com?

**Comment by fearphage** [comment]
Switch statements, like if statements, get slower the lower you go in.

```js
switch(foo): {
  case 1: //fastest
  case 2: // slower
  case 1000: // slowest
}
```

The same can be said for `if-else` statements with a ton of `else-if`'s.

`foo in bar` is constant time `O(1)`.
`switch` and `if` statements are `O(n)`

I can delete that from the pull request message. It was merely a bonus and not the focal point of this PR. The main point is the code is cleaner and easier to read and maintain in my opinion.

**Comment by fatso83** [comment]
Performance wise, this is probably quite a bit slower than a small lookup table that can be held in L1 cache, but we are talking nano-seconds here. On the big-Oh notation you are correct, but there is quite a bit of work involved in the lookup which is not done in a small switch statement, so there is a big C in those O(1)+C you are missing. Anyway, this is not a library focusing on performant code, and this code has not been identified as slow/problematic. Profile before refactoring for speed.

The important thing to me is readability, and I think you might have made an improvement in that regard. I would not mind merging it, but for later reference I think efforts are best spent on the bigger problems we are facing rather than micro-optimizations like this :-)

**Comment by fearphage** [comment]
I was **not** attempting to make a performance improvement. I regret mentioning it at all now. I was attempting to simplify the code.

**Comment by fatso83** [comment]
Haha, never mind. This seems legit, and I think it improves the readability, so I cannot see any reason not to merge it.

Thanks!

**Pull request merged**
