### PR TITLE
Added Github Actions

### PR DESCRIPTION
**Pull request by fearphage**
Setting up [Github Actions](https://github.com/features/actions).

### CODE REVIEW

**Comment by fearphage** [comment]
This is on hold until actions to be enabled for the project. :hourglass_flowing_sand: 

What are you waiting for?

**Comment by mroderick** [comment]
> This is on hold until actions to be enabled for the project.

Is it waiting on GitHub or on me?

**Comment by fearphage** [comment]
> Is it waiting on GitHub or on me?

If you clicked the Github actions link above and requested Sinon to be in the beta, that's all you can do. Then it's on Github at that point.

**Comment by mroderick** [comment]
ok, then I guess we'll just have to be patient

**Comment by fatso83** [comment]
Doesn't everyone have Github Actions at this point?

**Comment by fearphage** [comment]
> Doesn't everyone have Github Actions at this point?

Not Sinon. If they were active/available, [this](https://github.com/sinonjs/sinon/actions) would not 404 and there'd me an additional `actions` tab between pull requests and projects. You can see how it looks on [one of my projects](https://github.com/fearphage/actions).

**Comment by mroderick** [comment]
We have actions now :)

**Comment by fearphage** [comment]
This is fixed in #2076 now.

**Pull request closed without merging**
