### PR TITLE
CJSify fake-timer tests

### PR DESCRIPTION
**Pull request by jonnyreeves**
🚀

### CODE REVIEW

**Comment by mantoni** [comment]
Wrestling them down, one by one :facepunch: 
Very nice!

**Comment by jonnyreeves** [comment]
aye, slow going - but only a handful to do now - 2.0 is almost there (although I'm slightly concerned that we are going to get blocked by the docs website?)

**Comment by fatso83** [comment]
@jonnyreeves : I don't think the website should hold us back. We'll release 2.0 when 2.0 is finished, not when the revamped site is finished. That being said, me and Roderick had a appear.in session talking about this a week ago, and we have gotten the basic site generation up, so things are rolling. I'll be adding some articles as well so we can ship it with some new content too.

**Comment by jonnyreeves** [comment]
@mantoni good to land?

**Comment by mantoni** [comment]
:+1:

**Pull request merged**
