### PR TITLE
Warn of potential memory leaks

### PR DESCRIPTION
**Pull request by DullReferenceException**
#### Purpose (TL;DR) - mandatory

- Warn on the console if a potential memory leak is detected
- Allow adjusting of the leak detection threshold

Fixes https://github.com/sinonjs/sinon/issues/2356

#### How to verify - mandatory

1. Check out this branch
2. `npm install`
3. Call sinon.stub() 10,001 times in a loop
4. Verify that a console warning is output

#### Checklist for author

- [x] `npm run lint` passes
- [x] References to standard library functions are [cached](https://github.com/sinonjs/sinon/pull/1523).

### CODE REVIEW

**Comment by mantoni** [comment]
Great! Thank you 👍 

Can I ask you to use `printWarning` from our commons library?
https://github.com/sinonjs/commons/blob/e909e9746c32ba6c3c67e64b9ca5b62644cf343e/lib/deprecated.js#L48

This is safer and tests across various platforms to behave nicely.

I'm also not sure if the default threshold of `1000` isn't a bit low, since APIs like `sinon.createStubInstance` create lots of instances at once. What do you think @mroderick?

**Comment by DullReferenceException** [comment]
Updated, bumping default threshold to `10000` and using `deprecated.printWarning` instead.

**Comment by fatso83** [comment]
Great stuff and something that should have been there long ago. Not totally sold on the `track()` naming, though. I think it was easier to reason about what `push(collection, spy)` did than `track(spy)`, so I would have preferred if the tracking bits were internal details of "pushing into internal collection", as the latter is the main point. Maybe a simple rename is all that's needed (`addToCollection(spy)`?). These is all quite minor details, though, and we could merge it as is.

**Comment by DullReferenceException** [comment]
Good point on naming. Renamed to `addToCollection` as suggested.

**Comment by fatso83** [comment]
Thanks!

**Pull request merged**
