### PR TITLE
Fix: check configurable on a prop before creating (fixes #1456)

### LINKED ISSUE #1456: Attempting to configurable attribute of unconfigurable property.
### System info

**Node:** 8
**babel-polyfill:** 6.23.0
**core-js:** ^2.4.0
**phantomjs-prebuilt:** 2.1.14
**Sinon**: 2.3.1 (no issue) - 2.3.2 (has issue)

**What did you expect to happen?**

* It runs fine on chrome
* It throws error on phantomjs
* No issues with sinon 2.3.1. Issue after that.

**What actually happens**

I use `karma` run unit test. `webpack` for bundling and `babel` for code translation and polyfill. Running my unit test using `phantomjs` and i get the following error:

```sh
PhantomJS 2.1.1 (Windows 7 0.0.0) Positioning detectFlipPositionY Special cases Should return original if element exceeds limit on top and bottom FAILED
TypeError: Attempting to configurable attribute of unconfigurable property. in C:/Users/<dir/dir>/node_modules/babel-polyfill/dist/polyfill.js (line 4908)
```

**How to reproduce**

```js
describe("Positioning", () => {
    const sandbox = sinon.sandbox.create();

    const mockWindowWithAttr = (width = 100, height = 100) => {
        sandbox.stub(window, "innerWidth").value(width);
        sandbox.stub(window, "innerHeight").value(height);
    };

    beforeEach(() => {
        mockWindowWithAttr();
    });

    afterEach(() => {
        sandbox.restore();
    });

    it("test", () => {
        assert.isTrue(true);
    });
});
```

### UPDATE

Regression: https://github.com/sinonjs/sinon/pull/1419

* If I remove `configurable: true` then it works fine.

### PR DESCRIPTION
**Pull request by gyandeeps**
#### Purpose (TL;DR) - mandatory

Fixes #1456 by making sure propert is made `configurable` based on the object props.

@lucasfcosta  have created a fix with my beast understanding of your proposal. Feedback is welcome. Thanks

### CODE REVIEW

**Comment by fatso83** [comment]
Thanks for the fix. There is just one thing missing IMHO and that is that, based on its description, the test you are adding does not seem to have anything to do with the code you are adding.

I would move the existing test to the [issues test file](https://github.com/sinonjs/sinon/blob/e7dbfd78037effd626ccd8f4420b5c660409e56e/test/issues/issues-test.js) with a description that references the original issue (see the examples there). I would then add a test where the previous one was with code that does not reference the DOM, but rather creates an object with a property descriptor that would make Sinon fail previously, but that would pass now.

**Comment by gyandeeps** [comment]
@fatso83 Not sure what you mean but if you remove my source code changes and then run the test I added. It will fail. So i am not entirely sure what you mean by `you are adding does not seem to have anything to do with the code you are adding`

**Comment by fatso83** [comment]
It's a semantic issue. The code deals with "check configurable on a prop before creating", but the test is if `"it can stub window.innerHeight"`. There is no direct correlation between the two. Your fix is not directly related to the `window` property at all - that is just a biproduct of the missing check. (And, as far as I can see, it is not specific to sandboxes either - doesn't it affect non-sandboxed stubs as well?) Therefore, the test shouldn't really have to do with `window`. You should create an environment the test would fail in before the fix - regardless of you are running in a browser or on the server.

**Comment by gyandeeps** [comment]
Test code as been fixed. Let me know what you guys think.

**Comment by fatso83** [comment]
Great stuff. No objections other than that you could have squashed the fix/amended the previous, but since we can do this directly nowadays I squashed and merged it directly :smile: Thanks!

**Comment by mroderick** [comment]
This has become `v2.3.5`

**Comment by fatso83** [comment]
That was quick.

**Comment by mroderick** [comment]
> That was quick.

Too quick. The build fails in Safari 9.0 😨

**Comment by fatso83** [comment]
Too bad. The 2000th commit should have been a celebration of our great automation setup :1st_place_medal:  But :hankey: happens :smile:  At least we know about it!

@gyandeeps If you wonder went wrong you can check out [the logs from the Travis run](https://travis-ci.org/sinonjs/sinon/jobs/244828035):

```
  1) issues #1456 stub window innerHeight:
     Attempting to change access mechanism for an unconfigurable property.
  defineProperty@[native code]
  value@connect.html?url=ws%3A%2F%2Flocalhost%3A1034:1136:30
  connect.html?url=ws%3A%2F%2Flocalhost%3A1034:485:17
  connect.html?url=ws%3A%2F%2Flocalhost%3A1034:478:51
  connect.html?url=ws%3A%2F%2Flocalhost%3A1034:30238:58
  callFn@connect.html?url=ws%3A%2F%2Flocalhost%3A1034:49226:25
  run@connect.html?url=ws%3A%2F%2Flocalhost%3A1034:49218:13
  runTest@connect.html?url=ws%3A%2F%2Flocalhost%3A1034:49714:13
  connect.html?url=ws%3A%2F%2Flocalhost%3A1034:49820:19
  next@connect.html?url=ws%3A%2F%2Flocalhost%3A1034:49632:16
  connect.html?url=ws%3A%2F%2Flocalhost%3A1034:49642:11
  next@connect.html?url=ws%3A%2F%2Flocalhost%3A1034:49566:16
  connect.html?url=ws%3A%2F%2Flocalhost%3A1034:49605:11
  done@connect.html?url=ws%3A%2F%2Flocalhost%3A1034:49173:7
  callFn@connect.html?url=ws%3A%2F%2Flocalhost%3A1034:49244:11
  run@connect.html?url=ws%3A%2F%2Flocalhost%3A1034:49218:13
  next@connect.html?url=ws%3A%2F%2Flocalhost%3A1034:49580:13
  connect.html?url=ws%3A%2F%2Flocalhost%3A1034:49610:9
  timeslice@connect.html?url=ws%3A%2F%2Flocalhost%3A1034:44848:27
Error: Build failed: 1
```

**Comment by gyandeeps** [comment]
woops... sorry about this guys... I didn't test it on safari as I use windows... but regardless I wouldn't have thought of testing this on safari. Not sure what the right solution is here because this is very safari thing.

**Pull request merged**
