### PR TITLE
update source docs to document spying on accessors

### LINKED ISSUE #2160: current state of setter/getter spies
7.2.3:
https://sinonjs.org/releases/v7.2.3/spies/#using-a-spy-to-wrap-property-getter-and-setter

7.2.4 and onwards don't have this section of the docs.

For a patch release to remove a piece of functionality would be very questionable in terms of versioning so i assume the logic is still there in the source.

However, can someone please clear up what the situation is?

* Can we still spy on setters/getters this way?
* Where did the docs go?
* What is returned, if it works? a property descriptor? so it has a special signature different to all other spy calls?

Maybe the docs just went walkies by accident?

### PR DESCRIPTION
**Pull request by 43081j**
Fixes #2160 

 #### Purpose

Updating the source docs because only the generated ones were modified when the documentation for spying on accessors was introduced.

I also went ahead recently and fixed the typescript types again over on DefinitelyTyped so spying on an accessor returns the descriptor rather than a spy its self. Let me know if thats wrong in any way.

cc @fatso83

### CODE REVIEW

**Comment by fatso83** [comment]
Looks great. Care to also add the new info on the return types?

**Comment by 43081j** [comment]
It does already seem to mention that it returns the descriptor but im happy to change it a little if needed.

> spy.restore(). The returned spy is the object which replaced
> the original property descriptor. spy.get ===
> Object.getOwnPropertyDescriptor(object, 'property').get</code>.

**Comment by fatso83** [comment]
Yeah, it is a bit too cryptic and terse. Verboseness FTW.

**Comment by 43081j** [comment]
@fatso83 i updated the docs re the above. sorry for the long delay

**Comment by mroderick** [comment]
Pull requests like these are very valuable for projects like Sinon. Thank you 🏆

**Comment by mroderick** [comment]
The updated documentation will become visible, when the next release is out

**Pull request merged**
