### PR TITLE
Add a line recommending how to pronounce.

### PR DESCRIPTION
**Pull request by AdilKhn**
Adds a line on how to pronounce Sinon.

### CODE REVIEW

**Comment by fatso83** [comment]
While the idea is fine, could you please tell me where you got the idea that it is pronounced "see-non"? Referring to #43, you could se Christian give two versions:
- "sea-non", which is a Norwegian pronounciation
- "sigh-non", which is the English pronounciation

Given the global usage of Sinon it seems reasonable to use the English version as a standard.

**Comment by mantoni** [comment]
+1 for "sigh-non".

**Comment by fatso83** [comment]
@AdilKhn Just change the line as per above and this is fine to merge.

**Comment by fatso83** [comment]
Merged as  9bdf832

**Pull request closed without merging**
