### PR TITLE
Document spying on accessors

### LINKED ISSUE #1606: Documentation for Getter/Setter spying and stubbing
Hey all,

Is there currently documentation anywhere on how to use the getter and setter spying features outlined in #1205? If not, I could read through the code and tests and add that in if it's needed. I searched pretty hard and did not see it anywhere do I figured I'd ask. Thanks.

### PR DESCRIPTION
**Pull request by salomvary**
Closes #1606

 #### Purpose (TL;DR) - mandatory

Adds documentation for an undocumented feature.

 #### How to verify - mandatory
1. Check out this branch
2. Open `docs/_releases/latest/spies.md`

 #### Checklist for author

- [x] `npm run lint` passes
- [x] References to standard library functions are [cached](https://github.com/sinonjs/sinon/pull/1523).

### CODE REVIEW

**Comment by mroderick** [comment]
Documentation updates are very valuable to open source projects ⭐️ 

The documentation for Sinon is a bit special, so you'll have to also put the changes into all the previous releases for which this applies.

It's sort of hinted in https://github.com/sinonjs/sinon/blob/master/docs/CONTRIBUTING.md#example-documenting-a-fixed-bug, just not in a very obvious way.

Documentation is an area I'd like to significantly improve in 2019.

The feature was added with https://github.com/sinonjs/sinon/pull/692, which became part of `sinon@1.14.0`, so you'll have to add the changes to all the releases in [`docs/_releases`](https://github.com/sinonjs/sinon/tree/master/docs/_releases).

If you can manage to do the changes before March 9th, then we can merge it before it becomes four years after the feature was added 😊 

Thank you for contributing to documentation of Sinon 💯

**Comment by salomvary** [comment]
@mroderick Challenge accepted! :)

**Comment by salomvary** [comment]
For the record, the trick was:
```
git diff HEAD~ HEAD > doc.diff
find . -path '*docs/_releases/v*' -name spies.md | xargs -I {} patch {} doc.diff
```

**Comment by fatso83** [comment]
I am working on trying to make docs fixes a bit easier "for the rest of us", @mroderick. I'll have something soon.

**Comment by mroderick** [comment]
> I am working on trying to make docs fixes a bit easier "for the rest of us", @mroderick. I'll have something soon.

Let's talk about that during our call tomorrow ... one of the topics I'd like to talk about is documentation :)

**Comment by mroderick** [comment]
Thank you :)

**Pull request merged**
