### PR TITLE
Migrate Packaged Tests to use a Browserified Build.  

### PR DESCRIPTION
**Pull request by jonnyreeves**
Hell yes, CommonJS :rocket:

Browserify-shim has been added to take the global buster instance provided by the test-runner (rather than including it in the browserified bundle).  Tests are bundled into `tmp/` ahead of being executed.

`issues-test.js` had to change to have a stricter `requiresSupportFor` check as `process` is provided by browserify

`fake-xml-http-request-test.js` had to change to pick up the XMLHttpRequest instance from the global (window) rather than trying to get it from the `this` value in the closure.

Chagned the `'use strict'` requirement in the `test/` folder to be of the global form (typical of CommonJS modules) and moved all web-worker tests into their own folder as they require the `function` form of `'use strict'` and a built version of the code (at least for now...)

### CODE REVIEW

**Comment by fatso83** [comment]
This is great work, @jonnyreeves! LGTM. Quite a massive changeset :-)

**Comment by mantoni** [comment]
Awesome work! :+1: The CommonJS refactoring has come a long way.

**Comment by jonnyreeves** [comment]
@fatso83 
> Quite a massive changeset 

Agreed, sorry about that - I should have broken it up into a couple of logical commits; (one for Browserified build and one for the reformatting).  Let me know if you want me to make that change?

**Comment by fatso83** [comment]
@jonnyreeves I would not care about splitting it up. It's fine to my eyes.

**Comment by jonnyreeves** [comment]
Good to land? I've got more refactoring in the pipeline

**Comment by fatso83** [comment]
Good to land. Mind doing a quick rebase to resolve the conflicts?

**Comment by jonnyreeves** [comment]
Rebased.

**Pull request merged**
