### PR TITLE
add sandbox reset method

### PR DESCRIPTION
**Pull request by vitalets**
`sandbox.reset` allows you to reset all spies in sandbox. see #572 for details

### CODE REVIEW

**Comment by tung-dang** [comment]
Hi,
I can not find the document for `sandbox.reset` in sinon homepage. If it has not written yet, could someone please update it. 
Thank you.

**Comment by mroderick** [comment]
> Hi,
> I can not find the document for sandbox.reset in sinon homepage. If it has not written yet, could someone please update it. 
> Thank you.

The documentation website is due for an overhaul (I am working on it).

In the meantime, you can find up to date documentation in the source tree:

https://github.com/sinonjs/sinon/blob/master/docs/current/sandbox.md#sandboxreset

**Comment by tung-dang** [comment]
Thank you so much.

**Comment by gonzoyumo** [comment]
@mroderick just landed here after looking for information about `sandbox.reset()` :) It looks like the documentation has moved.

**Comment by fatso83** [comment]
@gonzoyumo https://github.com/sinonjs/sinon/blob/master/docs/release-source/release/sandbox.md

The source for the new docs is generally here: https://github.com/sinonjs/sinon/blob/master/docs/release-source

**Comment by gonzoyumo** [comment]
@fatso83 thanks, it's a bit sad it doesn't match http://sinonjs.org/docs/#sandbox though, as it was the primary resource where I (and maybe others) was looking.

**Comment by fatso83** [comment]
We are rewriting the docs for Sinon 2 and the new homepage. The current
homepage is for Sinon 1. Are there any omissions in the new docs?
-- 
Carl-Erik@mobile

**Pull request merged**
