### PR TITLE
Add `sandbox.reset()` description

### PR DESCRIPTION
**Pull request by jackbrown**
#### Purpose (TL;DR) - mandatory

Add docs for `sandbox.reset()` which was previously undocumented

#### How to verify - mandatory
1. Check out this branch (see github instructions below)
2. open `docs/current/sandbox.md`
3. review `sandbox.reset()` documentation

### CODE REVIEW

**Comment by mantoni** [comment]
You want to document `sandbox.restore()`, right? The description also says "Restores ...".

**Comment by mantoni** [comment]
Ah, no - you just copied the `restore` documentation. They're not the same thing.

**Comment by jackbrown** [comment]
what would be a better way of documenting this? maybe something like
`resets the internal state of all spies created through a sandbox`?

**Comment by mantoni** [comment]
@jackbrown Yes, that sounds more like it.

**Comment by jackbrown** [comment]
@mantoni thanks, updated.

**Comment by mantoni** [comment]
Great! I know it's a pain for such a small change, but can I ask you to squash the commits?

**Comment by jackbrown** [comment]
@mantoni no worries, done.

**Comment by mantoni** [comment]
Thanks! :+1:

**Comment by fatso83** [comment]
@mantoni : don't know if you noticed, but GH now allows you to select if you want to squash the commits when pressing the merge button. so we can do it ourselves in cases like this, unless you explicitly require the merge commit (which I don't think adds much for one-commit PRs).

**Comment by mantoni** [comment]
@fatso83 Yes, I know. I wasn't sure whether we want to use the feature here. I agree that it's a good idea for simple changes like these where we don't really need the merge commit.

**Pull request merged**
