### PR TITLE
Removed unnecessary module wrappers and double test run in NodeJS.

### PR DESCRIPTION
**Pull request by grassator**
This PR basically just removes IIFE and `makeApi` wrappers that are no longer necessary with CommonJS.

It also removes accidentally introduced in the previous PR double test run in NodeJS.

It's highly recommended to [view a diff for this PR with ignored whitespace](https://github.com/sinonjs/sinon/pull/869/files?w=1).

### CODE REVIEW

**Comment by grassator** [comment]
The build failure seems totally random and my branch built cleanly but I will look into it.

**Comment by mroderick** [comment]
I've restarted the build

**Comment by grassator** [comment]
@mroderick thanks, now the build succeeds. I've looked into the previously failing test and I'm really not sure how the failure could've happened.

I also ran the tests in different browsers a bunch of times and in PhantomJS on repeat 30 times with NodeJS 0.10, all with successful results. Then I did a couple more Travis builds on my branch for good measure, also green. This indeed looks like a freak Travis build error.

**Comment by mroderick** [comment]
Very nice!

(and thank you to github for `?w=1`)

**Comment by mantoni** [comment]
Great stutff! All the clutter goes away now! :tada:

**Pull request merged**
