### PR TITLE
sinon.resetHistory() does not reset history

### PR DESCRIPTION
**Pull request by rpgeeganage**
#### Purpose (TL;DR) - mandatory

Fix issue: https://github.com/sinonjs/sinon/issues/2016 `sinon.resetHistory()` does not reset history

Remove `createStubInstance` from `sinon.js` so same method from `sandbox` will be used.

 #### How to verify - mandatory
No tests added yet.
But followed below code snippet.
```js
const sinon = require('../../my_sinon_fork/sinon/');
const { assert } = require('referee');

describe('resetHistory', function() {
  var num = null;

  beforeEach(function() {
    num = sinon.createStubInstance(Number);
  });

  afterEach(() => {
    // Restore the default sandbox here
    sinon.restore();
  });

  describe('num.toFixed.resetHistory()', function() {
    it('num.toFixed.resetHistory()', function() {
      num.toFixed();
      assert.isTrue(num.toFixed.called);
      num.toFixed.resetHistory();
      assert.isFalse(num.toFixed.called);
    });
  });

  describe('sinon.resetHistory()', function() {
    it('sinon.resetHistory()', function() {
      num.toFixed();
      assert.isTrue(num.toFixed.called);
      sinon.resetHistory();
      assert.isFalse(num.toFixed.called);
    });
  });
});

```
Need to execute as follows.
`mocha test.js`
Got the following output.
```
  resetHistory
    num.toFixed.resetHistory()
      ✓ num.toFixed.resetHistory()
    sinon.resetHistory()
      ✓ sinon.resetHistory()


  2 passing (27ms)
```
 #### Checklist for author

- [x] `npm run lint` passes
- [x] References to standard library functions are [cached](https://github.com/sinonjs/sinon/pull/1523).

### CODE REVIEW

**Comment by rpgeeganage** [comment]
@fatso83 ,
Thank you for code snippet to recreate the bug.
The sample code in the https://runkit.com/fatso83/5cd3e47cdb83d1001a88c4c6 has a small issue.
(It may be I executed it wrong)
The problem is when I run `node test.js`, `beforeEach` block doesn't execute for each test.
I tested code in the description with `Mocha` library and got the expected output.
Please give you feedback on this.

**Comment by fatso83** [comment]
@rpgeeganage Basically you found a bug in `mini-mocha`: it's just a toy I hacked together for demo purposes in a small hour, so it turns out there are a few kinks here and there (like missing async support).

If things work using Mocha, then that's your verification :-)

**Comment by rpgeeganage** [comment]
@fatso83 ,
I like the `mini-mocha` lib  😄. I may use it for my small stuff too. If you need help with extending that library, I'm happy to lend you a hand.

Finally, I verified the output using the main `Mocha` library and added to the description. Are you ok with the changes?
What kind of a test case do you prefer for this ?

**Comment by fatso83** [comment]
Of course I'd love some help on `mini-mocha`!. It's quite useful for verifying issues without needing a full development environment and it would be quite useful to link to in a issue template, once it's a bit more feature complete (like async support).

With regards to the test case, I think just adding a simplified version of the last test above to the file https://github.com/sinonjs/sinon/blob/master/test/issues/issues-test.js would be sufficient. Something like `describe("2016", function(){ it("it should add instance stubs to the default sandbox"` where you just instantiate some `Foo` prototype.

**Comment by rpgeeganage** [comment]
@fatso83 ,
Thanks for the information. I'll update the test.

**Comment by rpgeeganage** [comment]
@fatso83,
I have added tests.

**Comment by fatso83** [comment]
@rpgeeganage We invite the ones who stick around, adding pull requests and seem interested in contributing to the project :-)

**Comment by rpgeeganage** [comment]
@fatso83 ,
Thanks for the information. I'll do more contributing to this project in the future :)
Are you ok with the tests?

**Comment by fatso83** [comment]
Thank you!

**Comment by rpgeeganage** [comment]
I'm honored to work in this repo.

**Pull request merged**
