### PR TITLE
Fix #2316: handle absent Promise for better IE11 support

### LINKED ISSUE #2316: Code for the Promise fake throws on IE11
**Describe the bug**
After the [recent change](#2293), IE11 throws an exception (Promise is not defined) [in this line](https://github.com/sinonjs/sinon/pull/2301/files#diff-452b8b6815a851fda3668042051feae7b63cee973b6fffdf4d93499474c986f8R41)

**To Reproduce**
1. User karma with karma-sinon
2. Run any test with sinon, and see error

**Expected behavior**
it should gracefully ignore that code piece if Promise is not defined in `self`.

**Context (please complete the following information):**

* Library version: 9.0.9
* Other libraries you are using: karma, karma-sinon

**Additional context**
I know. IE11 is not exactly a modern browser, but some companies like ours have to support them for their clients. And it sounds like the fix in sinon will be tiny

### PR DESCRIPTION
**Pull request by muodov**
#### Purpose (TL;DR) - mandatory

Fix #2316: Don't raise exceptions if Promise is not defined

 #### How to verify - mandatory
1. Check out this branch
2. `npm install`
3. Use the library in IE11

 #### Checklist for author

- [x] `npm run lint` passes
- [x] References to standard library functions are [cached](https://github.com/sinonjs/sinon/pull/1523).

### CODE REVIEW

**Review by fatso83 — APPROVED** [review]
Seems legit, but should probably test drive this in our Sauce labs suite.

**Comment by muodov** [comment]
@fatso83 The test suite (as far as I can see), is doing a similar check itself, so those tests are just skipped.
I tested it manually in our product (where it broke in the first place), and the fix worked there.
Please let me know what I can do to get this merged soon.

**Comment by mantoni** [comment]
Tests are already skipped correctly when `Promise` is not defined. Thank you @muodov 👍 

I can't make a release atm. If anyone else in @sinonjs/sinon-core could, that'd be great.

**Comment by mroderick** [comment]
This has been published as `sinon@9.2.2`

**Pull request merged**
