### PR TITLE
Deal with bundler issues

### PR DESCRIPTION
**Pull request by fatso83**
Ref the discussion regarding Webpack and other ES2015+ bundlers in #1805 and #1828 releasing a new major versionseems like a pragmatic, low-effort way of keeping noise out of our issue tracker.

This goes along with releasing [a patch for 5.x](https://github.com/sinonjs/sinon/compare/revert-esm-for-5x).

See #1805 and #1828 for details. The 'module' field in package.json caught some people by surprise.

### CODE REVIEW

**Comment by mroderick** [comment]
We usually provide a migration guide for each major version. Could we add one for this release as well?

**Comment by mroderick** [comment]
@fatso83 will you make the `5.1.1` pull request, so we can merge it and fix people's projects?

**Comment by fatso83** [comment]
sure

**Comment by mroderick** [comment]
I'm impatient 😉 

https://github.com/sinonjs/sinon/pull/1834

**Comment by fatso83** [comment]
I am not quite sure what to put in the 6.0 migration ... I am wondering if we should just put a placeholder there and release it now, updating it in hindsight, or if we should gather some experience with what to do with troubles affected by this?

I don't have access to any such projects of my own, atm. Remember if we got a link to such a thing recently?

**Comment by mroderick** [comment]
> I am not quite sure what to put in the 6.0 migration ... I am wondering if we should just put a placeholder there and release it now, updating it in hindsight, or if we should gather some experience with what to do with troubles affected by this?

That's a good question.

We let the pre-release of `5` be available for a long time, and it seems that @mantoni was the only one that really took it for a spin. I don't expect a pre-release of `6` to be much different.

> I don't have access to any such projects of my own, atm. Remember if we got a link to such a thing recently?

Are you saying that you don't have access to any projects that use all the bundling toys?

**Comment by fatso83** [comment]
> Are you saying that you don't have access to any projects that use all the bundling toys?
For some weird reason :smile: But I got a tip in #1835 to test out with chrisguttandin/midi-player and it seems there is no reason to have a migration guide for 6.0, as there doesn't seem to be any immediate issues now that #1833 has been implemented.

Bundler issues starting appearing with the `module` field in Sinon 5.1.0:
```
npm install && npm install sinon@5.1.0 && npm test

WARNING in ./test/mock/performance.js 4:9-13
"export 'stub' was not found in 'sinon'
 @ ./test/unit/midi-player.js

HeadlessChrome 0.0.0 (Linux 0.0.0) ERROR
...
HeadlessChrome 0.0.0 (Linux 0.0.0): Executed 0 of 6 SUCCESS (0 secs / 0 secs)
Firefox 60.0.0 (Ubuntu 0.0.0) ERROR
```

After running with the local Sinon 6 version, using `npm link sinon`:
```
HeadlessChrome 0.0.0 (Linux 0.0.0): Executed 9 of 9 SUCCESS (0.064 secs / 0.029 secs)
HeadlessChrome 0.0.0 (Linux 0.0.0): Executed 9 of 9 SUCCESS (0.064 secs / 0.029 secs)
Firefox 60.0.0 (Ubuntu 0.0.0): Executed 9 of 9 SUCCESS (0.09 secs / 0.014 secs)
TOTAL: 18 SUCCESS
```

**Comment by mroderick** [comment]
Excellent!

**Comment by janis91** [comment]
@fatso83 When you click "Releases" on the website and then "Docs" for v6.0.0 the migration guide is not linked. Maybe this is something that could be changed, too. I just wondered why there is no migration guide for v6.0.0. I found this issue linked in one of the last commits in the repo, but I was not looking in the "Guides" section. Maybe this is something that other users may stumble upon as well.

**Comment by fatso83** [comment]
This is me not knowing the structure of the site well enough. I remembed docs/guides/index.md b/docs/guides/index.md, but failed to see there is a "duplicate" file in https://github.com/sinonjs/sinon/blob/master/docs/_includes/docs/migration-guides.md. Seems this should be included in the other to avoid this situation appearing.

**Comment by fatso83** [comment]
The "guide" is [linked from the Guides section](http://sinonjs.org/guides/), btw.

**Comment by fatso83** [comment]
@janis91 The doc issue will be fixed by #1838. Thanks for noticing it!

**Comment by janis91** [comment]
You're welcome :-)

**Pull request merged**
