### PR TITLE
Update nise to 1.4.1

### PR DESCRIPTION
**Pull request by tzrh**
#### Purpose (TL;DR) - mandatory

It would be useful to have https://github.com/sinonjs/nise/pull/45 included.

#### How to verify - mandatory
1. Check out this branch
2. `npm install`
3. `npm test`

#### Checklist for author

- [x] `npm run lint` passes
- [x] References to standard library functions are [cached](https://github.com/sinonjs/sinon/pull/1523).

### CODE REVIEW

**Comment by mroderick** [comment]
@tzrh when you install `sinon` from NPM it uses the latest `nise`, because of the caret range: https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

```
$ npm install sinon@latest --save-dev

+ sinon@6.1.3
added 15 packages from 330 contributors and audited 18 packages in 3.072s
found 0 vulnerabilities

$ npm ls nise
tmp-1859@1.0.0 /Users/mroderick/tmp-1859
└─┬ sinon@6.1.3
  └── nise@1.4.2
```

Perhaps it is frozen in your `package-lock.json` / `yarn.lock`?

**Comment by tzrh** [comment]
I missed that, thanks!

**Comment by tzrh** [comment]
@mroderick Is it possible that https://github.com/sinonjs/sinon/issues/1656 has happened again? In http://sinonjs.org/releases/sinon-6.0.1.js, I don't see [these lines](https://github.com/sinonjs/nise/blob/v1.4.1/lib/fake-xhr/index.js#L180-L183).

**Comment by mroderick** [comment]
@tzrh I think you're correct!

Do you have a proposal for how we can ensure that the packaged build is done with the latest versions?

**Comment by tzrh** [comment]
Adding `npm update` to https://github.com/sinonjs/sinon/blob/master/scripts/postversion.sh might make sense. I'm not sure if that's taking that script further away from it's original purpose though.

**Pull request closed without merging**
