### PR TITLE
fix: toString calls

### PR DESCRIPTION
**Pull request by joscha**
Backports #833 to 1.17

cc @fatso83 @mroderick

### CODE REVIEW

**Comment by mroderick** [comment]
Thanks @joscha

**Comment by joscha** [comment]
No worries! Please let me know when 1.17.3 is ready!

Cheers!

**Comment by joscha** [comment]
@mroderick @fatso83 Is there anything I can do to help get a new release of the 1.17 branch out?

**Comment by joscha** [comment]
68bcf73bb3def5dd3dd89eea5b39455a9c1d8d0d - Thank you!!

**Comment by fatso83** [comment]
Wow, that was fast. I was about to tell you, but I guess you had some kind of ping going on to tell you when something happened in the repo :-)

**Comment by joscha** [comment]
Haha, I wish - was purely incidental - greenkeeper sent me an emai for another repositoryl :)

**Pull request merged**
