### PR TITLE
Fix #1308: Add /downloads/ folder to new site

### LINKED ISSUE #1308: Issue with old releases no longer being published on new site
now that the new site is live (https://github.com/sinonjs/sinon/issues/1220), a lot of the old releases are not published anymore, this is an issue as a lot of repo's depend on older releases

https://github.com/search?q=http%3A%2F%2Fsinonjs.org%2Freleases%2F&type=Code&utf8=%E2%9C%93 (47,412 results found) a lot of these no longer work, can you publish all of the older releases again so that downstream repo's continue working properly? 

one specific example, there are many more but this repo I use relies on http://sinonjs.org/releases/sinon-1.12.2.js in it's bower.json which is no longer there which causes other issues

https://github.com/danielspaniel/ember-data-factory-guy/blob/v1.13.10/bower.json

### PR DESCRIPTION
**Pull request by mroderick**
#### Purpose (TL;DR)

Fix #1308 and #1306 by adding legacy releases to the `docs/releases/` folder

### CODE REVIEW

**Comment by mroderick** [comment]
Ping @mantoni

**Comment by mantoni** [comment]
Thanks Morgan! Is the `/downloads/` folder being renamed to `/releases/` somehow? I can't see where. If it isn't this wouldn't fix all the broken links.

**Comment by mroderick** [comment]
> Thanks Morgan! Is the /downloads/ folder being renamed to /releases/ somehow? I can't see where. If it isn't this wouldn't fix all the broken links.

I obviously did not look closely enough at the legacy site ...

**Comment by mantoni** [comment]
Hah! And I completely forgot that we did set it up last weekend 🙈

**Comment by mroderick** [comment]
@mantoni I believe I've fixed it

**Comment by mantoni** [comment]
Yep. Looks good.

**Pull request merged**
