### PR TITLE
Fix 1026 in 2.x

### LINKED ISSUE #1026: sinon.stub an object with 'watch' function doesn't stub the watch function
- Sinon version : 1.12.2 [Edit, 1.17.3]
- Environment   : JS test framework with Intern

**What did you expect to happen?**

`sinon.stub( { watch: function() {} } )` to stub the object and the watch method. 

**What actually happens**

watch is not stubbed in FIREFOX.

**How to reproduce**

```
var stubbedObject = sinon.stub({ watch: function() {} });
stubbedObject.watch.args[1];
```

stubbedObject.watch does not have property 'args'

This only fails in Firefox. The problem is that when sinon.stub iterates over the functions of an object to stub them, it makes sure it doesn't stub the same function twice. It uses an object to keep track of all of the functions seen already. Object should have a prototype method called 'watch' (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/watch) but right now, only Firefox implements this. 

When .stub walks through the object's functions, and compares them to what it has 'seen' (in /lib/sinon/util/core/walk.js line 19) but the seen object has methods on it already.

Currently, the check if the function is seen is simply '!seen[k]'. I think it should be 'seen[k] !== true' seeing as that directly corresponds to the way the function records if an object is seen (with seen[k] = true). I have tested this and it works.

### PR DESCRIPTION
**Pull request by mroderick**
This is a PR for `master`, it fixes #1026.

It is just the commits from #1030 ported to `master`.

However, there has been some changes that causes `collection-test` to fail.

I will investigate later, unless someone beats me to it

### CODE REVIEW

**Comment by fatso83** [comment]
Fails a test in all Node versions

**Comment by mroderick** [comment]
> Fails a test in all Node versions

Yeah, I am still trying to figure out why

**Comment by mroderick** [comment]
@fatso83 I've fixed the tests by making sure that `collection.stub` does not get a new behaviour, when we're updating the behaviour of `walk`.

Do you agree with the changes?

**Comment by fatso83** [comment]
Seems fine

**Comment by mroderick** [comment]
Great! I am merging this!

**Pull request merged**
