### PR TITLE
Fix inaccurate and confusing document for 'fake.yields' and 'fake.yieldsAsync'.

### PR DESCRIPTION
**Pull request by bingtimren**
#### Purpose (TL;DR) - mandatory

Fix issue https://github.com/sinonjs/sinon/issues/2031 by rewriting document and code example for fake.yields and fake.yieldsAsync

### CODE REVIEW

**Comment by mantoni** [comment]
This is a lot better. Thank you 💯!

**Comment by fatso83** [comment]
Sane documentation! What more could one ask for? Great job.

**Comment by mantoni** [comment]
@fatso83 Hm, this doesn't show up on our website. I always get confused about the place where the documentation has to be done. Was it done in the right place? Or is there something wrong with the automatic deployment?

**Comment by fatso83** [comment]
Weird. It seems like the right file ... All github systems are operational as well ...

**Comment by mantoni** [comment]
Do I have to cut a release for the docs to be published?

**Comment by fatso83** [comment]
Nope. It is supposed to be immediately updated.

**Pull request merged**
